import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PDF Saas Platforn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressContentEditableWarning>
      <body className={cn(
        'min-h-screen font-sans antialiased',
        inter.className
      )}>
        {children}
      </body>
    </html>
  );
}
